let oct = 010;
let bin = 0b10, hexa = 0x10;
let dia, nota;
dia = 25;
nota = 9.7;
document.write (`Dia: ${dia}`);
document.write("<br>");
document.write (`Nota: ${nota}`);
document.write("<br>");
document.write(oct,"<br>",bin,"<br>",hexa);